// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuI4vtTf9OXPtMl3Cux2jf_KT_TlJQSGc',
    appId: '1:976092059625:web:b2f5d88c34ff00e8791d78',
    messagingSenderId: '976092059625',
    projectId: 'workos-16f39',
    authDomain: 'workos-16f39.firebaseapp.com',
    storageBucket: 'workos-16f39.appspot.com',
    measurementId: 'G-54PF8HC2NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmMY9Zd90nFVRDaQ8Qy57B2FroogwBeg8',
    appId: '1:976092059625:android:b812cf2b81a973b2791d78',
    messagingSenderId: '976092059625',
    projectId: 'workos-16f39',
    storageBucket: 'workos-16f39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVPAhRkWmGsOJkiZ3Ql1P3npEHfcNbnIA',
    appId: '1:976092059625:ios:18d7d0f2a29cbaac791d78',
    messagingSenderId: '976092059625',
    projectId: 'workos-16f39',
    storageBucket: 'workos-16f39.appspot.com',
    iosClientId: '976092059625-onf1mrds2du7s485kadnadc0p9nu1nqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.workos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVPAhRkWmGsOJkiZ3Ql1P3npEHfcNbnIA',
    appId: '1:976092059625:ios:18d7d0f2a29cbaac791d78',
    messagingSenderId: '976092059625',
    projectId: 'workos-16f39',
    storageBucket: 'workos-16f39.appspot.com',
    iosClientId: '976092059625-onf1mrds2du7s485kadnadc0p9nu1nqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.workos',
  );
}
